language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
before_install:
  - yes | sdkmanager "platforms;android-29"
  - cd sample/
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
script:
   - ./gradlew :app:build
