name: DEPLOY
on:
    push:
        branches:
            - release
jobs:
    ci:
        name: Build & Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            
            - name: Prepare environment
              env:
                SONATYPE_GPG_FILE_CONTENT: ${{ secrets.SONATYPE_GPG_FILE_CONTENT }}
                SIGN_GPG_FILE: ${{ secrets.SIGN_GPG_FILE }}
              run:  |
                sudo bash -c "echo '$SONATYPE_GPG_FILE_CONTENT' | base64 -d > '$SIGN_GPG_FILE'"
                mv $SIGN_GPG_FILE sample/

            - name: Build Release
              run: cd sample; ./gradlew :annotation:assemble; ./gradlew :processor:assemble; ./gradlew :router:assembleRelease

            - name: Publish Router
              env:
                SIGN_ID: ${{ secrets.SIGN_ID }}
                SIGN_PASSWORD: ${{ secrets.SIGN_PASSWORD }}
                SIGN_GPG_FILE: ${{ secrets.SIGN_GPG_FILE }}
                SONATYPE_ID: ${{ secrets.SONATYPE_ID }}
                SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
                SONATYPE_PASS: ${{ secrets.SONATYPE_PASS }}
              run: cd sample; ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository